export const adminMenu = [
  ["dashboard", "Dashboard"],
  ["website", "Edit website"],
  ["uploads", "Photos & uploads"],
  ["projects", "Projects"],
  ["project-categories", "Project categories"],
  ["technologies", "Project technologies"],
  ["skills", "Skills"],
  ["skill-categories", "Skill categories"],
  ["experience", "Experience"],
  ["education", "Education"],
  ["certifications", "Certifications"],
  ["engineering", "Engineering"],
  ["blog", "Blog posts"],
  ["blog-categories", "Blog categories"],
  ["blog-tags", "Blog tags"],
  ["contact-messages", "Contact messages"],
  ["media", "Media library"],
  ["resumes", "Resume"],
  ["social-links", "Social links"],
  ["site-settings", "Website settings"],
  ["profile", "Profile"],
];
