export interface Media {
  id: number;
  url: string;
  alt_text?: string | null;
  original_name?: string;
  mime_type?: string;
  width?: number | null;
  height?: number | null;
}
export interface Content {
  id: number;
  sort_order?: number;
  title?: string;
  name?: string;
  slug?: string;
  summary?: string;
  description?: string;
  body?: string;
  excerpt?: string;
  headline?: string;
  introduction?: string;
  biography?: string;
  availability?: string;
  focus?: string;
  learning?: string;
  philosophy?: string;
  public_email?: string;
  phone?: string;
  location?: string;
  role?: string;
  organization?: string;
  institution?: string;
  qualification?: string;
  field_of_study?: string;
  responsibilities?: string;
  coursework?: string;
  issuer?: string;
  credential_id?: string;
  credential_url?: string;
  issued_on?: string;
  expires_on?: string;
  started_on?: string;
  ended_on?: string;
  is_current?: boolean;
  published_at?: string;
  updated_at?: string;
  is_featured?: boolean;
  status?: string;
  proficiency?: string;
  icon?: string;
  repository_url?: string;
  demo_url?: string;
  platform?: string;
  label?: string;
  url?: string;
  employment_type?: string;
  reading_minutes?: number;
  problem?: string;
  solution?: string;
  architecture?: string;
  challenges?: string;
  outcomes?: string;
  target_users?: string;
  key_features?: string;
  database_design?: string;
  api_architecture?: string;
  lessons_learned?: string;
  future_improvements?: string;
  meta_title?: string;
  meta_description?: string;
  cover?: Media | null;
  avatar?: Media | null;
  media?: Media | null;
  pdf?: Media | null;
  logo?: Media | null;
  architecture_image?: Media | null;
  database_image?: Media | null;
  category?: Content | null;
  project?: Content | null;
  technologies?: Content[];
  tags?: Content[];
  gallery?: Media[];
  key?: string;
  value?: unknown;
}
export interface PageData<T> {
  data: T[];
  meta?: { current_page: number; last_page: number; total: number };
}
export type SearchParams = Record<string, string | string[] | undefined>;
